### ISSUE TITLE
Can't insert into a map when iterating over a duplicate

### ISSUE THREAD

**Issue by DanielWaterworth** [ruby-concurrency/ref#8] opened 2013-07-23 10:01 UTC
This fails in 1.9.3

    m = Ref::WeakKeyMap.new
    a = Object.new
    m[a] = "test"
    n = m.dup
    n.each do |k, v|
      m[Object.new] = "something"
    end

**Comment by jdantonio** [comment] 2015-01-27 15:54
@DanielWaterworth Are you still interested in exploring this functionality? I've read the discussion a couple of times and think the use case makes sense, although I would probably elect to implement it as a method with another name rather than overriding `dup`. Anyway, the original maintainer recently agreed to transfer this gem to the `ruby-concurrency` org and allow us to help him maintain it (we wanted to use `Ref::WeakKeyMap` in `concurrent-ruby`). It's been a long time since you created this issue so I'll understand if you've moved on to other projects. If you're still interested I'd love to discuss this further otherwise I'd like to close the issue.

Issue #16 is a conversation in which we are planning a 2.0 release. Please feel free to add to that conversation as well.

**Comment by DanielWaterworth** [comment] 2015-01-27 16:24
@jdantonio, I'm no longer using ref in anything live so I don't have a stake in the result any longer.

**Comment by jdantonio** [comment] 2015-01-27 16:32
@DanielWaterworth Cool. Thanks for getting back to me so quickly. I'll close the issue. If you ever use the gem again please don't hesitate to give us feedback.

**Comment by pitr-ch** [comment] 2015-01-27 18:05
After reading, this sounds like a bug to me. I know we have limited people and time :/ but It might be better to keep it open for others to find when they run into the issue or if anybody would want to fix it. It might be fixed by just adding `#initialize_copy` method.

**Comment by jdantonio** [comment] 2015-01-27 22:13
@pitr-ch I think the original author makes a compelling case for this being expected behavior, but I do think it would be an interesting feature to add. I've reopened it for the reasons you've mentioned.

**Comment by jdantonio** [comment] 2015-05-15 02:06
Addressed in #34.

**Closed** 2015-05-15 02:06 UTC
